[general]
import = [
   "~/.config/alacritty/theme.toml"
]

[env]
TERM = "alacritty"

[window]
padding = { x = 5, y = 5 }
decorations = "None"
# opacity = 0.9
dynamic_padding = false

[font]
normal = { family = "CaskaydiaCove Nerd Font Mono", style = "Regular" }
bold = { family = "CaskaydiaCove Nerd Font Mono", style = "Bold" }
italic = { family = "CaskaydiaCove Nerd Font Mono", style = "Italic" }
bold_italic = { family = "CaskaydiaCove Nerd Font Mono", style = "Bold Italic" }
size = 14.0

[cursor]
style = { shape = "Block", blinking = "On" }
unfocused_hollow = true

[scrolling]
history = 10000
multiplier = 6

[selection]
save_to_clipboard = true

# [bell]
# animation = "EaseOutExpo"
# duration = 0

[keyboard]
bindings = [
    { key = "V", mods = "Control|Shift", action = "Paste" },
    { key = "C", mods = "Control|Shift", action = "Copy" },
    { key = "Back", mods = "Control|Alt", chars = "\u0015" }, 
    # { key = "Key0", mods = "Control", action = "ResetFontSize" },
    # { key = "Equals", mods = "Control", action = "IncreaseFontSize" },
    # { key = "Minus", mods = "Control", action = "DecreaseFontSize" },
]
